<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Add sale</h3>
                </div>
                <div class="panel-body">
                    <form enctype="multipart/form-data" action="" method="post">
                        <div class="form-group">
                            <?=$this->saleForm->productId?>
                        </div>
                        <div class="form-group">
                            <?=$this->saleForm->percentage?>
                        </div>
                        <div class="form-group">
                            <?=$this->saleForm->startDate?>
                        </div>
                        <div class="form-group" style="margin-bottom: 10px;">
                            <?=$this->saleForm->endDate?>
                        </div>
                        <div id="date-error" class="panel panel-danger" style="display: none;">
                            <div class="panel-heading">
                                <h3>Error Starting date cannot be larger or equal to the ending date</h3>
                            </div>
                        </div>
                        <div class="btn-group-justified">
                            <div class="btn-group">
                                <input id="submit" value="Submit" type="submit" class="btn btn-default" />
                            </div>
                            <div class="btn-group">
                                <a href="/shop-user/list-all-products/" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $(".datepicker").datepicker({
            showOn: 'focus',
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy-mm-dd',
            //minDate: new Date(currentYear, currentMonth, currentDate)
        });
        
        $(".datepicker").change(function () {
            $("#submit").attr("type", "submit");
            var dates = $(".datepicker");
            var startDateVal = $(dates[0]).val();
            var endDateVal = $(dates[1]).val();
            if(startDateVal != '' && endDateVal != '') {
                var startDate = new Date($(dates[0]).val());
                var endDate = new Date($(dates[1]).val());
                console.log($(dates[0]));
                if(startDate >= endDate) {
                    $("#date-error").show("shake", 500);
                    $("#submit").attr("type", "button");
                }
                else {
                    $("#date-error").hide("slide", 1000);
                }
            }
        });
    });
</script>