
<script>
    $(document).ready(function(){
        
         google.charts.load('current', {'packages':['corechart']});
        google.charts.setOnLoadCallback(drawChart);

        function drawChart() {

          var data = google.visualization.arrayToDataTable([
              
            ['product', 'Number of sales'],
            <?php foreach ($this->products as $product): 
                if ($product['numOfSale'] > 0) : ?>
                        
            ['<?= $product["name"]?>',     <?= $product["numOfSale"] ?>],
                   
           <?php endif;
           endforeach  ?>
          ]);

          var options = {
            title: 'Product sales number chart'
          };

          var chart = new google.visualization.PieChart(document.getElementById('piechart'));

          chart.draw(data, options);
        }
         google.charts.load('current', {'packages':['corechart']});
         google.charts.setOnLoadCallback(revenueChart);
        function revenueChart() {

          var data = google.visualization.arrayToDataTable([
              
            ['product', 'Total Revenue'],
            <?php foreach ($this->products as $product): 
                if ($product['moneyGained'] > 0) : ?>
                        
            ['<?= $product["name"]?>',     <?= $product["moneyGained"] ?>],
                   
           <?php endif;
           endforeach  ?>
          ]);

          var options = {
            title: 'Product Revnue chart'
          };

          var chart = new google.visualization.PieChart(document.getElementById('revchart'));

          chart.draw(data, options);
        }
        
         google.charts.load('current', {'packages':['corechart']});
         google.charts.setOnLoadCallback(quantity);
         
        function quantity(){
            var data = google.visualization.arrayToDataTable([
              
            ['product', 'Total quantity'],
            <?php foreach ($this->products as $product): 
                if ($product['quantity'] > 0) : ?>
                        
            ['<?= $product["name"]?>',     <?= $product["quantity"] ?>],
                   
           <?php endif;
           endforeach  ?>
          ]);

          var options = {
            title: 'Product Quantity chart'
          };

          var chart = new google.visualization.PieChart(document.getElementById('quantitychart'));

          chart.draw(data, options);
        }
        
        google.charts.load('current', {'packages':['corechart']});
         google.charts.setOnLoadCallback(price);
         
        function price(){
            var data = google.visualization.arrayToDataTable([
              
            ['product', 'price'],
            <?php foreach ($this->products as $product): 
                if ($product['price'] > 0) : ?>
                        
            ['<?= $product["name"]?>',     <?= $product["price"] ?>],
                   
           <?php endif;
           endforeach  ?>
          ]);

          var options = {
            title: 'Price chart'
          };

          var chart = new google.visualization.PieChart(document.getElementById('pricechart'));

          chart.draw(data, options);
        }
        
    })
         
     

 </script>
     <div class="row">
         <div class="col-md-6">
            <div id="piechart" style="width: 100%; height: 500px;"></div>
         </div>
         <div class="col-md-6">
              <div id="revchart" style="width: 100%; height: 500px;"></div>
         </div>
     </div>
 <div class="row" style="margin-top: 20px;">
           <div class="col-md-6">
               <div id="quantitychart" style="width: 100%; height: 500px;"></div>
            </div>
            <div class="col-md-6">
               <div id="pricechart" style="width: 100%; height: 500px;"></div>
            </div>
    </div>

        
