

<div class="panel-heading panel-primary">
        <center class="danger"><h1>All Products  </h1></center>

</div>
<table class="table table-bordered">
<?php
	foreach($this->products as $key => $value)
	{
			echo "<tr class='danger'><td>".$value['id']."</td>".
			"<td >".$value['name']."</td>".
			"<td>".$value['description']."</td>".
			"<td> <a class='btn btn-info' href='list-product-details/productId/".$value['id']."'role='button'>Details </a> </td>".
			"<td> <a class='btn btn-danger' href='delete-product/productId/".$value['id']."'role='button'>Delete </a> </td>".
			"<td> <a class='btn btn-danger' href='edit-product/productId/".$value['id']."'role='button'>Edit </a> </td></tr>";
	}

 ?>

</table>

<a class='btn btn-danger' href='add-product'role='button'>Add Product </a>
<a class='btn btn-danger' href='list-current-sale'role='button'>List all sale </a>




