    <div class="panel panel-default">
        <div class="panel-heading">
            <h1><?=$this->productStatistics['name']?></h1>
        </div>
    <div class="panel-body">
<!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
                <h3>
                    <?php echo $this->productStatistics['numOfSale'];?>
                </h3>

              <h4> Number of sale </h4>
            </div>
            <div class=" icon ">
              <i class="  glyphicon glyphicon-shopping-cart icon"></i>
            </div>
            <div class="small-box-footer"> <i class="fa fa-arrow-circle-right"></i></div>
          </div>
          
          
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
                <h3>
                  <?php echo $this->productStatistics['moneyGained'];?>
                </h3>

              <h4>Money Gained</h4>
            </div>
            <div class="icon">
              <i class="glyphicon glyphicon-usd"></i>
            </div>
            <div class="small-box-footer"> <i class="fa fa-arrow-circle-right"></i></div>
          </div>
        </div>
        
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3><?php echo  $this->productStatistics['rate'];?></h3>

              <h4>Rating</h4>
            </div>
            <div class="icon">
              <div class=" glyphicon glyphicon-star ">
                <div style="position: static; background: #DA8028; display: block;" class="star-rating" title="Rated <?= $this->productStatistics['rate'] ?> out of 5">
                    <?php for ($i=0; $i< $this->productStatistics['rate'] ; $i++ ): ?>
                        <span class="star filled"> </span>
                    <?php endfor; ?>
                    <?php  for ($i= $this->productStatistics['rate']; $i < 5; $i++): ?>
                        <span class="star"> </span>
                    <?php endfor; ?>
                </div>
            </div>
            </div>
            <div class="small-box-footer"> <i class="fa fa-arrow-circle-right"></i></div>
          </div>
        </div>
        
        
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
                <h3>
                    <?php echo $this->productStatistics['quantity'];?>
                </h3>

              <h4>Quantity</h4>
            </div>
            <div class="icon">
              <i class="glyphicon glyphicon-stats"></i>
            </div>
            <div  class="small-box-footer"> <i class="fa fa-arrow-circle-right"></i></div>
          </div>
        </div>
        <!-- ./col -->
      </div>
      <!-- /.row -->



      <div class="callout callout-danger">
          
            <div class="icon">
              <i class="glyphicon glyphicon-king"></i>
            </div>
          <h2>Top product in <span><u><b><i><?=$this->categoryStatistics['cName']?><i></b></u></span> category </h2>
          <div class="inner">
                <h3>
                      <?php echo " Product Name :".$this->categoryStatistics['pName']; ?>
                </h3>

                <h3>
                      <?php echo "Number of sale :".$this->categoryStatistics['max'];?>
                </h3>
          </div>
          
        </div>
 
