<div class="container">
    <div class="row">
        <div class="col-md-2">
            
        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Shop statistics</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-hover table-responsive">
                        <th class="text-center">Products</th>  
                        <th class="text-center">Sold units</th> 
                        <th class="text-center">Price</th> 
                        <th class="text-center">Revenue</th>
                        <?php
                            foreach($this->productStatistics as $key => $value)
                            {
                                $moneys=$value['numOfSale']*$value['price'];
                                echo "<tr>"
                                . "<td class='text-center'>".$value['name']."</td>".
                                "<td class='text-center'>".$value['numOfSale']."</td>".
                                "<td class='text-center'>".$value['price']."</td>".
                                "<td class='text-center'>".$moneys."</td>"
                                        . "</tr>";
                            }

                         ?>

                    </table>
                </div>
            </div>

        </div>
    </div>
</div>
