<?php
    $languageSession = new Zend_Session_Namespace("language");
    $language = "";
    if($languageSession->language == "Ar")
        $language = "_ar";
    $col_counter = 0;
    $user = $this->user->read();
//    
?>

<header id="header">
        <div class="header-middle"><!--header-middle-->
                <div class="container">
                        <div class="row">
                                <div class="col-sm-4">
                                        <div class="logo pull-left">
                                                <a href="/"><img src="<?= $this->baseUrl() ?>/img/home/logo.png" alt="" /></a>
                                        </div>
                                        <div class="btn-group pull-right">
                                                <div class="btn-group">
                                                        <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                                                <?php if($language == "_ar"): ?>
                                                                        العربية
                                                                <?php else: ?>
                                                                        English

                                                                <?php endif; ?>
                                                                <span class="caret"></span>
                                                        </button>
                                                        <ul class="dropdown-menu">
                                                            <li><a href="/index/toggle-language">
                                                                <?php if($language == "_ar"): ?>
                                                                        English
                                                                <?php else: ?>
                                                                         العربية

                                                                <?php endif; ?>
                                                                </a></li>
                                                        </ul>
                                                </div>

                                        </div>
                                </div>
                                <div class="col-sm-8">
                                        <div class="shop-menu pull-right">
                                                <ul class="nav navbar-nav">
                                                        <li><a href="<?= $this->baseUrl() ?>"><i class="fa fa-star"></i> Home </a></li>
                                                    <?php if ($user && $user->privilege=="customerUser"): ?>
                                                        <li><a href="<?= $this->baseUrl() ?>/customer-user/view-wish-list"><i class="fa fa-star"></i> Wishlist</a></li>
                                                        <li><a href="<?= $this->baseUrl() ?>/customer-user/view-cart"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                                                    <?php endif; 
                                                    if($user): ?>
                                                        <li><a href="<?= $this->baseUrl() ?>/user/logout"><i class="fa fa-lock"></i> Logout</a></li>
                                                    <?php else : ?>
                                                        <li><a href="<?= $this->baseUrl() ?>/user/login"><i class="fa fa-lock"></i> Login</a></li>
                                                    <?php endif; ?>
                                                </ul>
                                        </div>
                                </div>
                        </div>
                </div>
        </div><!--/header-middle-->

        <div class="header-bottom"><!--header-bottom-->
                <div class="container">
                        <div class="row">
                            <div class="col-sm-9">

                            </div>
                            <div class="col-sm-3">
                                    <div class="search_box pull-right">
                                        <form method="post" action="/index/search-products" name="search_form">
                                            <input name="search_product" type="text" placeholder="Search"/>
                                        </form>
                                    </div>
                            </div>
                        </div>
                </div>
        </div><!--/header-bottom-->
</header><!--/header-->


<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 padding-right">
                    <div class="features_items"><!--features_items-->
                            <h2 class="title text-center">Category Items</h2>
                             <div class="product-list">
                                <?php foreach ($this->products as $product) { 
                                    $col_counter ++;
                                    if ($col_counter-1 % 3 == 0) : ?>

                                        <div class="row">
                                    <?php endif; ?>
                                            <div class="col-sm-4">
                                                <div class="entry-product">
                                                    <a href="/index/product-details/product_id/<?= $product['id'] ?>" class="Product-link">
                                                    <?php if (($product['saleflag']== 1) && $product['percentage']): ?>
                                                        <span class="onsale">Sale!</span>
                                                    <?php endif; ?>
                                                    </a>
                                                    <div class="entry-featured">
                                                        <a  style="cursor: pointer" href="/index/product-details/product_id/<?= $product['id'] ?>">
                                                            <img style="width:100%" src="/images/<?= $product['photo'] ?>" >
                                                            <div class="star-rating-container aggregate">
                                                                <div class="star-rating" title="Rated <?= $product['rate'] ?> out of 5">
                                                                    <?php for ($i=0; $i< $product['rate'] ; $i++ ): ?>
                                                                        <span class="star filled"> </span>
                                                                    <?php endfor; ?>
                                                                    <?php  for ($i= $product['rate']; $i < 5; $i++): ?>
                                                                        <span class="star"> </span>
                                                                    <?php endfor; ?>
                                                                </div>
                                                            </div>
                                                        </a>
                                                        <?php
                                                        if ($user && $user->privilege=="customerUser") : 
                                                            if($product['quantity'] > 0): 
                                                                if ($user->id == $product['shopping_cart_user_id'] ) : ?>
                                                                    <a rel="nofollow"  data-product_id = "<?= $product['id'] ?>" data-user_id = "<?= $user->id ?>" class="increment-quantity">
                                                                        Add to cart
                                                                    </a>
                                                                <?php
                                                                else: ?>
                                                                    <a rel="nofollow"  data-product_id = "<?= $product['id'] ?>" data-user_id = "<?= $user->id ?>" class="add-to-cart">
                                                                        Add to cart
                                                                    </a>
                                                                <?php
                                                                endif;
                                                                if ( $user->id == $product['wishlist_user_id']  ) : ?>
                                                                        <a class="btn btn-danger remove-from-wishlist" data-product_id = "<?= $product['id'] ?>" data-user_id = "<?= $user->id ?>" > Remove From wish list </a>
                                                                <?php
                                                                else: ?>
                                                                        <a class="btn btn-primary add-to-wishlist" data-product_id = "<?= $product['id'] ?>" data-user_id = "<?= $user->id ?>" > Add to wish list </a>

                                                                <?php    
                                                                endif;
                                                            endif;
                                                        endif;
                                                             ?>
                                                    </div>
                                                    <div class="entry-wrap">
                                                        <header class="entry-header">
                                                            <h3 style="text-align: left;">
                                                                <a class="product-name"  href="/index/product-details/product_id/<?= $product['id'] ?>">
                                                                     <?=($language == "_ar" && ! empty($product['name'.$language]) ? $product['name'.$language] : $product['name']) ?></a>
                                                            </h3>
                                                            <div style="text-align: left;"class="price">
                                                            <?php if (($product['saleflag']== 1) && $product['percentage']): ?>
                                                                <del>
                                                                    <span class="Price-amount amount">
                                                                    <span class="Price-currencySymbol">$</span><?= $product['price'] ?></span>
                                                                </del> 
                                                                <ins>
                                                                    <span class="Price-amount amount">
                                                                    <span class="Price-amount amount">$</span><?= $product['price']* ((100-$product['percentage']) / 100) ?>
                                                                    </span>
                                                                </ins>
                                                            </div>
                                                            <?php else : ?>
                                                                <ins>
                                                                    <span class="Price-amount amount">
                                                                    <span class="Price-currencySymbol">$</span><?= $product['price'] ?>
                                                                    </span>
                                                                </ins>
                                                            <?php
                                                            endif;
                                                            ?>


                                                        </header>
                                                    </div>
                                                </div>
                                            </div>

                                        <?php  if ($col_counter % 3 == 0) : ?> 
                                                </div>
                                    <?php endif;
                                } 
                                ?>
                                         </div>

                    </div><!--features_items-->



                </div>
            </div>
        </div>
</section>






    <div class="x-cart-notification">
        <div class="x-cart-notification-icon loading">
            <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
        </div>
        <div class="x-cart-notification-icon added">
            <i class="fa fa-check" aria-hidden="true"></i>
        </div>
    </div>



