<?php 
    $user = $this->user->read();
    $languageSession = new Zend_Session_Namespace("language");
    $language = "_ar";
    if($languageSession->language == "Ar")
        $language = "_ar";
    ?>
<div class="container">
    <div class="product-details section">
        <div class="row">
            <div class="col-md-8">
                <img style="width: 100%"src ="/images/<?= $this->product['photo'] ?>" >
            </div>
            <div class="col-md-4">
                <h2> About the product </h2>
                <p> Product Name:  <?= ($language == "_ar" && ! empty($this->product['name'.$language]) ? $this->product['name'.$language] : $this->product['name']) ?> </p>
                <p> <?= $this->product['description'] ?> </p>
                <?php if ($this->product['percentage']): ?>
                                    <del>
                                        <span class="Price-amount amount">
                                        <span class="Price-currencySymbol">$</span><?= $this->product['price'] ?></span>
                                    </del> 
                                    <ins>
                                        <span class="Price-amount amount">
                                        <span class="Price-amount amount">$</span><?= $this->product['price']* ((100-$this->product['percentage']) / 100) ?>
                                        </span>
                                    </ins>
                                </div>
                                <?php else : ?>
                                    <ins>
                                        <span class="Price-amount amount">
                                        <span class="Price-currencySymbol">$</span><?= $this->product['price'] ?>
                                        </span>
                                    </ins>
                                <?php
                                endif;
                                ?>
            </div>
        </div>
        <?php  
        if (!($this->user->isEmpty() )) :
            if (! $this->rate->hasBeenRated($this->product['id'], $user->id ) ): ?>
                <div class="rating-form" style="height:150px; ">
                    <form>
                        <fieldset>
                            <span class="star-cb-group">
                                <?php 
                                $counter =5;
                                foreach ($this->rating_form->getElement('Rating')->getMultiOptions() as $label => $value) : ?>

                                <input id="rating-<?= $counter ?>" type="radio" value="<?= (6-  $value); ?>" name="rating" />
                                 <label for= "rating-<?= $counter ?>"><?php echo $counter; ?></label>

                                <?php 
                                    $counter --;
                                    endforeach; 
                                ?>
                                <input type="radio" id="rating-0" name="rating" value="0" class="star-cb-clear" /><label for="rating-0">0</label>
                            </span>
                        </fieldset>
                        <input  data-product_id = "<?= $this->product['id'] ?>" data-user_id = "<?= $user->id ?>" disabled= "true" type="button" class="btn btn-primary submit-rate-button" value="Add rating">

                    </form> 
                </div>
        <?php
            endif;
        ?>  

        <div class="comments-list">
            <?php
            foreach ($this->all_comments as $comment){
            ?>
            <div class="comment"><?= $user->userName.": ". $comment['comment'] ?> </div>
            <?php }
            ?>
        </div>
        <div class="comments-form">
             <?php 
             echo $this->comments_form;
             ?> 
            <input type="hidden" data-user_name = "<?= $user->userName ?>" data-product_id = "<?= $this->product['id'] ?>" data-user_id = "<?= $user->id ?>"  type="button" class="hidden-button">

        </div>
<?php endif; ?>