<?php  
    $user = $this->user->read();
?>
<div class="product-details">
    <img src ="<?= $this->product['photo'] ?>" >
    <div class="product-desc">
        <p> <?= $this->product['description'] ?> </p>
    </div>
</div>
<div class="rating-form" style="height:150px; ">
    <form>
        <fieldset>
            <span class="star-cb-group">
                <?php 
                $counter =5;
                foreach ($this->rating_form->getElement('Rating')->getMultiOptions() as $label => $value) : ?>
               
                <input id="rating-<?= $counter ?>" type="radio" value="<?= (6-  $value); ?>" name="rating" />
                 <label for= "rating-<?= $counter ?>"><?php echo $counter; ?></label>

                <?php 
                    $counter --;
                    endforeach; 
                ?>
                <input type="radio" id="rating-0" name="rating" value="0" class="star-cb-clear" /><label for="rating-0">0</label>
            </span>
        </fieldset>
        <input  data-product_id = "<?= $this->product['id'] ?>" data-user_id = "<?= $user->id ?>" disabled= "true" type="button" class="btn btn-primary submit-rate-button" value="Add rating">
       
    </form> 
</div>
<div class="comments-form">
     
</div>
<script>
$(document).ready(function(){
    var ratingValue;
    $(document).on('change', '[type*="radio"]', function(e) {
        ratingValue = $(this).attr('value');
        $('.submit-rate-button').removeAttr('disabled');
      });
       $(document).on('click', ".submit-rate-button", function(e) {
        
                $.ajax({
                    url: "/customer-user/put-rate",
                    type: "GET",
                    dataType:'json',
                    context: this,
                    data: {product_id: $(this).attr("data-product_id"), user_id : $(this).attr("data-user_id"), rating : ratingValue},
                    success: function(){
                        $('.rating-form').empty();
                        $('.rating-form').append('<img style="width:60px;" src="/img/ajax-loader1.gif" >');
                        setTimeout(function(){
                            $('.rating-form').empty();
                            $('.rating-form').append('<p style="font-size: 20px" > Thanks for submitting your feedback</p>');
                        }, 1800)

                    },
                    error:function (xhr, ajaxOptions, thrownError){
                        console.log(xhr);
                        console.log(ajaxOptions);
                        console.log(thrownError);
                     } 
                 });
           
            });
      
  });
  </script>