<html>
    <head>
        <meta charset="utf-8">
   	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()?>/node_modules/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()?>/node_modules/bootstrap/dist/css/bootstrap-theme.min.css" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()?>/node_modules/admin-lte/dist/css/AdminLTE.min.css" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()?>/node_modules/admin-lte/dist/css/skins/skin-blue.css" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()?>/node_modules/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()?>/css/style.css" /> 
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()?>/node_modules/jquery-ui-dist/jquery-ui.min.css" />
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl()?>/node_modules/jquery-ui-dist/jquery-ui.theme.min.css" />
  
        <!-- Ionicons -->
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/node_modules/ionicons/dist/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/node_modules/admin-lte/dist/css/AdminLTE.min.css">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/node_modules/admin-lte/dist/css/skins/_all-skins.min.css">
        <!-- iCheck -->
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/iCheck/flat/blue.css">
        <!-- Morris chart -->
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/morris/morris.css">
        <!-- jvectormap -->
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
        <!-- Date Picker -->
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/datepicker/datepicker3.css">
        <!-- Daterange picker -->
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/daterangepicker/daterangepicker.css">
        <!-- bootstrap wysihtml5 - text editor -->
        <link rel="stylesheet" href="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

        
        <script src="<?= $this->baseUrl()?>/node_modules/tether/dist/js/tether.min.js"></script>
	<script src="<?= $this->baseUrl()?>/node_modules/jquery/dist/jquery.min.js"></script>
	<script src="<?= $this->baseUrl()?>/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="<?= $this->baseUrl()?>/node_modules/admin-lte/dist/js/app.min.js"></script>
        <script src="<?= $this->baseUrl()?>/node_modules/jquery-ui-dist/jquery-ui.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/node_modules/admin-lte/dist/js/app.min.js"></script>
        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
        <script src="<?= $this->baseUrl() ?>/node_mudules/admin-lte/dist/js/pages/dashboard.js"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="<?= $this->baseUrl() ?>/node_mudules/admin-lte/dist/js/demo.js"></script>
        <style>
            table td {
                vertical-align: middle !important;
                padding-top : 12px !important;
                padding-bottom: 12px !important;
            }
            .checkbox, .radio {
                margin : 0;
            }
            input[type='checkbox']{
                position: static !important;
            }
            .form-group{
                margin: 0;
            }
            table {
               background: #222d32;
               color: white;
            }
            table tr {
                transition: 0.5s;
            }
            table tr:hover{
                 background:   #ccc  !important;
                 color: black;
            }
        </style>

    </head>
    <body class="hold-transition skin-blue fixed sidebar-mini">
        <div class="wrapper">
            <div class="content-wrapper">
                <div class="content-header">

        <?php
            $userSession = new Zend_Session_Namespace('user');
           
            include_once "html/shopuser-header.php";
            include_once "html/shopuser-sidebar.php";
            
            $auth = Zend_Auth::getInstance();
            $identity = $auth->getIdentity();
//            if (!empty($identity)) {

           ?>
<!--            <a href="//
            <?php
            // echo $this->baseUrl()
            ?>/user/logout"> Logout </a>-->
        <?php
//
//
//            }
//
//
 ?>
        



        <?php echo $this->layout()->content; ?> 
        
        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>

        
        <script src="<?=$this->baseUrl()?>/node_modules/raphael/raphael-min.js"></script>
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/morris/morris.min.js"></script>
        <!-- Sparkline -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/sparkline/jquery.sparkline.min.js"></script>
        <!-- jvectormap -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <!-- jQuery Knob Chart -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/knob/jquery.knob.js"></script>
        <!-- daterangepicker -->
        <script src="<?=$this->baseUrl()?>/node_modules/moment/min/moment.min.js"></script>
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/daterangepicker/daterangepicker.js"></script>
        <!-- datepicker -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/datepicker/bootstrap-datepicker.js"></script>
        <!-- Bootstrap WYSIHTML5 -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
        <!-- Slimscroll -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/slimScroll/jquery.slimscroll.min.js"></script>
        <!-- FastClick -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/plugins/fastclick/fastclick.js"></script>
        <!-- AdminLTE App -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/dist/js/app.min.js"></script>
        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/dist/js/pages/dashboard.js"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="<?=$this->baseUrl()?>/node_modules/admin-lte/dist/js/demo.js"></script>
    </body>
</html>
