<div class="container">
    <?php foreach($this->userWishList as $product): ?>
    
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h4><?=$product['name']?></h4>
            </div>
            
            <div class="col-md-3">
                <h4><a  href="/index/product-details/product_id/<?=$product['id']?>/"><img class="img-responsive img-rounded" src="<?= $this->baseUrl()?>/images/<?=$product['photo']?>" width="250" height="150"/></a></h4>
            </div>
            
            <div class="col-md-3">
                <h5><?=$product['description']?></h5>
            </div>
            <div class="col-md-3">
                <button data-editing="true" data-product_id="<?=$product['id']?>" data-user_id="<?=$product['userId']?>"  class="btn btn-danger btn-block remove-from-wishlist" style="position: static;display:block">Remove from wish list</button>
            </div>
        </div>
    </div>
    
    <?php endforeach ?>
</div>
