<?php
$cart = $this->cart;
?>
<div class="container">
    <div class="row">
        <div class="col-md-8">
        <table class="shop_table shop_table_responsive cart" cellspacing="0">
            <thead>
                <tr>
			<th class="product-remove">&nbsp;</th>
			<th class="product-thumbnail">&nbsp;</th>
			<th class="product-name">Product</th>
			<th class="product-price">Price</th>
			<th class="product-quantity">Quantity</th>
			<th class="product-subtotal">Total</th>
		</tr>
            </thead>
            <tbody>	
		<tr class="cart_item">
                    <td class="product-remove">
                        <a href="http://demo.theme.co/shop-integrity/cart/?remove_item=7cbbc409ec990f19c78c75bd1e06f215&amp;_wpnonce=c94fc7486c" class="remove" title="Remove this item" data-product_id="70" data-product_sku="">×</a>	
                    </td>
                    <td class="product-thumbnail">
                        <a href="http://demo.theme.co/shop-integrity/product/flying-ninja/"><img width="180" height="180" src="<?= $cart['product_photo'] ?>" class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image" alt="poster_2_up"></a>					
                    </td>
                    <td class="product-name" data-title="Product">
                        <a href="http://demo.theme.co/shop-integrity/product/flying-ninja/"><?= $cart['product_name'] ?></a>
                    </td>
                    <td class="product-price" data-title="Price">
                        <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span><?= $cart['product_price'] ?></span>
                    </td>
                    <td class="product-quantity" data-title="Quantity">
                        <div class="quantity">
                            <input type="number" step="1" min="0" max="" name="cart[7cbbc409ec990f19c78c75bd1e06f215][qty]" value="<?= $cart['quantity']?>" title="Qty" class="input-text qty text" size="4" pattern="[0-9]*" inputmode="numeric">
                        </div>
                    </td>
                    <td class="product-subtotal" data-title="Total">
                        <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span><?= $cart['quantity'] * $cart['product_price'] ?> </span>
                    </td>
                </tr>
		<tr>
                    <td colspan="6" class="actions">
                        <div class="coupon">
                            <label for="coupon_code">Coupon:</label> 
                            <input type="text" name="coupon_code" class="input-text" id="coupon_code" value="" placeholder="Coupon code">
                            <input type="submit" class="button" name="apply_coupon" value="Apply Coupon">

                        </div>
                        <input type="submit" class="button" name="update_cart" value="Update Cart" disabled="">
                            <input type="submit" class="button" name="apply_coupon" value="Apply Coupon">
                            <input type="hidden" id="_wpnonce" name="_wpnonce" value="c94fc7486c">
                            <input type="hidden" name="_wp_http_referer" value="/shop-integrity/cart/">
                    </td>
		</tr>

            </tbody>
        </table>
        <div class="cart-collaterals">
            <div class="cart_totals">
                <h2>Cart Totals</h2>
                <table cellspacing="0" class="shop_table shop_table_responsive">
                    <tbody>
                        <tr class="cart-subtotal">
                            <th>Subtotal</th>
                            <td data-title="Subtotal"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>24.00</span></td>
                        </tr>
                        <tr class="order-total">
                            <th>Total</th>
                            <td data-title="Total"><strong><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>24.00</span></strong> </td>
                        </tr>

                    </tbody>
                </table>
            <div class="wc-proceed-to-checkout">		
                    <a href="http://demo.theme.co/shop-integrity/checkout/" class="checkout-button button alt wc-forward">
            Proceed to Checkout</a>
            </div>
        </div>


</div>
            
        </div>
    </div>
</div>