
<div class="container">
    <div class="row">
        <div class="col-md-4">
            
        </div>
        <div class='col-md-4'>
            <div class='panel panel-info'>
                <div class='panel-heading'>
                    <h3 class='text-center'>
                        Registration Form
                    </h3>
                </div>
                <div class='panel-body'>
                    <form action='' method='post'>
                        <div class='form-group'>
                            <?=$this->signup_form->username?>
                        </div>
                        <div class='form-group'>
                            <?=$this->signup_form->email?>
                        </div>
                        <div class='form-group'>
                            <?=$this->signup_form->fname?>
                        </div>
                        <div class='form-group'>
                            <?=$this->signup_form->lname?>
                        </div>
                        <div class='form-group'>
                            <?=$this->signup_form->privilege?>
                        </div>
                        <div class='form-group'>
                            <?=$this->signup_form->password?>
                        </div>
                        <div class='form-group'>
                            <?=$this->signup_form->confirm_password?>   
                        </div>
                        <div class="error panel panel-danger" style="display: none;">
                            <div class="panel-heading">
                                User is registered.<br>
                                Please check username and email
                            </div>
                        </div>
                        <div class='btn-group-justified'>
                            <div class='btn-group'>
                                <input type='submit' class='btn btn-default' />
                            </div>
                            <div class='btn-group'>
                                <a href='/user/login' class='btn btn-danger'>Cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
</div>

<?php if($this->error): ?>
    <script>
        $(".error").show("bounce", 750);
    </script>
<?php endif ?>
    
}