<div class="container">
    <div class="row">
        <div class="col-md-4">
            
        </div>
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3>Email specifications</h3>
                </div>
                <div class="panel-body">
                    <form action="" method="post">
                        <div class="form-group">
                            <?=$this->contactForm->subject?>
                        </div>
                        <div class="form-group">
                            <?=$this->contactForm->content?>
                        </div>
                        <div class="btn-group-justified">
                            <div class="btn-group">
                                <input type='submit' class="btn btn-default" value="Send" />
                            </div>
                            <div class="btn-group">
                                <a href="/admin/" class="btn btn-danger">Cancel</a>
                            </div>
                        </div>
                    </form>    
                </div>
            </div>
            
            
        </div>
    </div>
</div>