<?php
    echo "<table class='table table-responsive table-hover'>";
    
    echo "<tr><th>Username</th><th>Email</th><th>Status</th><th>Privilages</th></tr>";
    foreach($this->userList as $record) {
       echo "<tr>";
       echo "<td>".$record['userName']."</td>";
       echo "<td>".$record['email']."</td>";
       echo "<td><a id='".$record['id']."' href='/admin/change-status/id/".$record['id']."/status/".$record['status']."/' style='text-decoration: none;'><i class='".($record['status'] == '1' ? "text-success fa fa-dot-circle-o" : "text-danger fa fa-ban")."' aria-hidden='true'></i></a></td>";
       echo "<td><a id='".$record['id']."' href='/admin/change-privilege/id/".$record['id']."/privilege/".$record['privilege']."/' style='text-decoratorion: none;'><img class='img-responsive img-circle' width='25' height='25' src='/img/".$record['privilege'].".ico' /></a></td>";
       echo "</tr>";
    }
    echo "</table>";
?>
