<table class="table table-hover table-responsive">
    <tr>
        <th class='text-center'>Category name</th>
        <th class='text-center'>Edit category name</th>
        <th class='text-center'>Delete Category</th>
        <?php
            foreach($this->categories as $category) {
                echo "<tr>";
                echo "<td class='text-center'>".$category['name']."</td>";
                echo<<<EOL
                <td class='text-center'>
                    <button type="button" class="text-primary btn-transparent" data-toggle="modal" data-target="#category
EOL;
                echo $category['id'];
                echo<<<EOL
">
                        <i class="fa fa-pencil-square-o"></i>
                    </button>
                    <div class="text-left modal fade" id="category
EOL;
                echo $category['id'];
                echo<<<EOL
" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form method='post' action='/admin/manage-categories/id/
EOL;
                echo $category['id'];
                echo<<<EOL
'>
                                <div class="modal-header">
                                    <button type="button" class="btn-transparent close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Rename category 
EOL;
                echo $category['name'];
                echo <<<EOL
                
                                    </h4>
                                </div>
                                <div class="modal-body">
EOL;
                echo "<div class='form-group'";
                echo $this->updateCategoryForm->category;
                echo "</div>";
                
                echo <<<EOL
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
EOL;
                //echo $this->updateCategoryForm->update;
                echo<<<EOL
                                    <button type="submit" name="submit" id="submit" class="btn btn-primary">Save changes</button>
                                </div>
                            </form>
                            </div>
                        </div>
                    </div>
                </td>
EOL;
                echo "<td class='text-center'><a href='/admin/delete-category/id/".$category['id']."'><i class='text-danger fa fa-times'></i></a></td>";
            }
            
        ?>
    </tr>
</table>
<div class="container">
    <div class="row">
        
        <div class="col-md-12">
            <?php
                echo<<<EOL
                    <button type="button" class="btn btn-default btn-lg btn-block" data-toggle="modal" data-target="#newCategory">
                        Add new category
                    </button>
                    <div class="text-left modal fade" id="newCategory" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            
                            <form name='new_category' method='post' action=''>
                            <div class="modal-content">
                                
                                <div class="modal-header">
                                    <button type="button" class="btn-transparent close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Adding new Category  
                                    </h4>
                                </div>
                                <div class="modal-body">
                                    
EOL;
                echo $this->addCategoryForm;

                echo <<<EOL
                                    
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    <button type='submit' id='new_category_button' class="btn btn-primary">Save changes</button>
                                </div>
                                </form>
                                
                            </div>
                        </div>
                    </div>
EOL;
       
            ?>
        </div>
    </div>
</div>